# Exception Handling
This document contains a summary of Exception Handling features in Kotlin.

## Exception throwing
Exceptions can be thrown with the `throw` keyword. All classes that derive from `Throwable` can be thrown. The default exception class implements `Throwable` and custom exceptions can be created by implementing the `Exception` class.
```kotlin
class NewException(
	description: String
): Exception(descriptioin)

throw NewException("This went wrong")
```

## Recovery
Exceptions are handled through a `try catch` block. Multiple `catch` blocks, all catching different exceptions can be put underneath a `try` block. Exceptions will be caught if the class they are derived from is one of the `catch` blocks. E.g. all exceptions are caught when `exception` is one of the blocks.
```kotlin
try {
	runSomething()
} catch (e: NewException) {
	println("The new one!")
} catch (e: Exception) {
	println("Something else went wrong" )
}
```